// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbhWPal0xhzf4cOmG8a3VYx5nzu7FIf0U',
    appId: '1:106038024434:web:7f465f0c12152c39d1186b',
    messagingSenderId: '106038024434',
    projectId: 'barya-app-6cfad',
    authDomain: 'barya-app-6cfad.firebaseapp.com',
    storageBucket: 'barya-app-6cfad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHTYa4AudnVT7B_vWUKe95ibO4sEF53dg',
    appId: '1:106038024434:android:0e0d562a4966161dd1186b',
    messagingSenderId: '106038024434',
    projectId: 'barya-app-6cfad',
    storageBucket: 'barya-app-6cfad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7E-Zb1kHJzgdrVn_hkIQGsx53K0cvZ-E',
    appId: '1:106038024434:ios:116940b4143d199ad1186b',
    messagingSenderId: '106038024434',
    projectId: 'barya-app-6cfad',
    storageBucket: 'barya-app-6cfad.firebasestorage.app',
    iosBundleId: 'com.example.appbarya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7E-Zb1kHJzgdrVn_hkIQGsx53K0cvZ-E',
    appId: '1:106038024434:ios:116940b4143d199ad1186b',
    messagingSenderId: '106038024434',
    projectId: 'barya-app-6cfad',
    storageBucket: 'barya-app-6cfad.firebasestorage.app',
    iosBundleId: 'com.example.appbarya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbhWPal0xhzf4cOmG8a3VYx5nzu7FIf0U',
    appId: '1:106038024434:web:48fc4f05c1bdcaa9d1186b',
    messagingSenderId: '106038024434',
    projectId: 'barya-app-6cfad',
    authDomain: 'barya-app-6cfad.firebaseapp.com',
    storageBucket: 'barya-app-6cfad.firebasestorage.app',
  );

}